config/routes.rb
OpenParty::Application.routes.draw do

  get "/about", to: "miscellaneous#about", as: :about

  resources :events, :except => :destroy do
    resources :enrolments
    resources :topics
  end
  resources :records

  match "/auth/:provider/callback", to: "sessions#create"
  match "/auth/failure", to: "sessions#new"
  get "/login", to: "sessions#new", as: :login
  get "/logout", to: "sessions#destroy", as: :logout

  resource :user, :only => [:show, :edit, :update, :destroy]
  get "/signup", to: "users#new", as: :signup

  resources :registrations, only: [:create]
  get "/checkin", to: "registrations#new", as: :checkin

  root :to => "events#index"

end

app/models/topic.rb
class Topic < ActiveRecord::Base
  belongs_to :event;
  belongs_to :user;
  attr_accessible :detail, :estimated_minutes, :name, :user_id
  validates_presence_of  :detail, :estimated_minutes, :name, :user_id
  validates_uniqueness_of :name, { scope: :event_id}

end

app/controllers/topics_controller.rb
class TopicsController < ApplicationController
  def create
    @event = Event.find(params[:event_id])
    @topic = @event.topics.new(params[:topic].merge(user_id: current_user.id))
    respond_to do |format|
      if @topic.save
        format.js
        format.html
      else
        format.js
      end
    end
  end

  def show
    @event = Event.find(params[:event_id])
    @topic = @event.topics.find(params[:id])
  end
end

app/helpers/topics_helper.rb
module TopicsHelper
end

app/views/topics/_form.html.erb
<%= form_for([@event, @event.topics.build], remote: true) do |f| %>
  <div class="field">
    <%= f.label :name, "话题名称"%><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :estimated_minutes, "预计时长(分钟)" %><br />
    <%= f.text_field :estimated_minutes %>
  </div>
  <div class="field">
    <%= f.label :detail, "详情" %><br />
    <%= f.text_area :detail %>
  </div>
  <div class="actions">
    <%= f.submit '提交话题' %>
  </div>
<% end %>

app/views/topics/_topic.html.erb
<div class="topic">
  <%= link_to topic.name, event_topic_url(topic.event, topic) %>
</div>

app/views/topics/create.js.erb
<% if @topic.errors.empty? %>
  $('<%= escape_javascript(render @topic) %>').appendTo($('#topics'));
<% else %>
  $('<span class="error-message"><%= escape_javascript(@topic.errors.full_messages.join(',')) %></span>').appendTo($('#new_topic_form'))
<% end %>

app/views/topics/show.html.erb
<h1><%= @topic.name %></h1>
<p>预计时长：<%= @topic.estimated_minutes %>分钟</p>
<p><%= @topic.detail %>