config/routes.rb
OpenParty::Application.routes.draw do

  get "/about", to: "miscellaneous#about", as: :about

  resources :events, :except => :destroy do
    resources :enrolments
    resources :topics
  end
  resources :records

  match "/auth/:provider/callback", to: "sessions#create"
  match "/auth/failure", to: "sessions#new"
  get "/login", to: "sessions#new", as: :login
  get "/logout", to: "sessions#destroy", as: :logout

  resource :user, :only => [:show, :edit, :update, :destroy]
  get "/signup", to: "users#new", as: :signup

  resources :registrations, only: [:create]
  get "/checkin", to: "registrations#new", as: :checkin

  root :to => "events#index"

end

app/models/record.rb
class Record < ActiveRecord::Base
  attr_accessible :user_id, :event_id, :text, :title

  belongs_to :user
  belongs_to :event

  validates_presence_of :user_id, :event_id, :text, :title

end

app/controllers/records_controller.rb
class RecordsController < ApplicationController
  skip_before_filter :ensure_logged_in, only: [ :index, :show ]

  # GET /records
  # GET /records.json
  def index
    @records = Record.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @records }
    end
  end

  # GET /records/1
  # GET /records/1.json
  def show
    @record = Record.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @record }
    end
  end

  # GET /records/new
  # GET /records/new.json
  def new
    @record = Record.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @record }
    end
  end

  # GET /records/1/edit
  def edit
    @record = current_user.records.find(params[:id])
  end

  # POST /records
  # POST /records.json
  def create
    @record = current_user.records.new(params[:record])

    respond_to do |format|
      if @record.save
        format.html { redirect_to @record, notice: 'Record was successfully created.' }
        format.json { render json: @record, status: :created, location: @record }
      else
        format.html { render action: "new" }
        format.json { render json: @record.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /records/1
  # PUT /records/1.json
  def update
    @record = current_user.records.find(params[:id])

    respond_to do |format|
      if @record.update_attributes(params[:record])
        format.html { redirect_to @record, notice: 'Record was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @record.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /records/1
  # DELETE /records/1.json
  def destroy
    @record = Record.find(params[:id])
    @record.destroy

    respond_to do |format|
      format.html { redirect_to records_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/records_helper.rb
module RecordsHelper
end

app/views/records/_form.html.erb
<%= form_for(@record) do |f| %>
  <% if @record.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@record.errors.count, "error") %> prohibited this record from being saved:</h2>

      <ul>
      <% @record.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :event_id %><br />
    <%= f.select :event_id, options_from_collection_for_select(Event.past_events, :id, :name) %>
  </div>
  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :text %><br />
    <%= f.kindeditor :text%>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/records/_record.html.erb
<%= link_to record.title, record %>

app/views/records/edit.html.erb
<h1>Editing record</h1>

<%= render 'form' %>

<%= link_to 'Show', @record %> |
<%= link_to 'Back', records_path %>

app/views/records/index.html.erb
<% @records.each do |record| %>
  <h2><%= link_to record.title, record %></h2>
  <p><%= record.user.name %>发表于<%= I18n.l(record.created_at, format: :long) %></p>
  <p>相关活动：<%= link_to record.event.name, record.event %></p>
<% end %>

<br />

<%= link_to 'New Record', new_record_path %>

app/views/records/new.html.erb
<h1>New record</h1>

<%= render 'form' %>

<%= link_to 'Back', records_path %>

app/views/records/show.html.erb
<h2><%= @record.title %></h2>
<%= link_to '修改', edit_record_path(@record) if @record.user == current_user %>
<%= social_share_button_tag(@record.title) %>
<p>
  <span>作者：<%= @record.user.name %></span>
  <span>关联活动：<%= link_to @record.event.name, @record.event %></span>
</p>
<p>
<%= raw @record.text %>
</p>

<%= render template: "/layouts/_uyan.html" %>