config/routes.rb
OpenParty::Application.routes.draw do

  get "/about", to: "miscellaneous#about", as: :about

  resources :events, :except => :destroy do
    resources :enrolments
    resources :topics
  end
  resources :records

  match "/auth/:provider/callback", to: "sessions#create"
  match "/auth/failure", to: "sessions#new"
  get "/login", to: "sessions#new", as: :login
  get "/logout", to: "sessions#destroy", as: :logout

  resource :user, :only => [:show, :edit, :update, :destroy]
  get "/signup", to: "users#new", as: :signup

  resources :registrations, only: [:create]
  get "/checkin", to: "registrations#new", as: :checkin

  root :to => "events#index"

end

app/models/event.rb
class Event < ActiveRecord::Base
  has_many :enrolments, :dependent => :delete_all
  has_many :topics, :dependent => :delete_all
  has_many :records, :dependent => :delete_all
  has_many :registrations, :dependent => :delete_all


  validates_presence_of :name, :hold_date, :location, :poster_url, :detail;

  def past_event?
    self.hold_date < Date.today
  end

  def pending_event?
    !past_event?
  end

  def self.past_events
    self.where("hold_date < ?", Date.today).order("hold_date DESC")
  end

  def self.pending_events
    self.where("hold_date >= ?", Date.today).order("hold_date DESC")
  end

  def self.past_event_names
    past_events.select("name, id").collect { |e| e.attributes.values }
  end

  def self.current_event
    pending_events.last
  end

end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  skip_before_filter :ensure_logged_in, only: [ :index, :show ]
  before_filter :ensure_is_admin, except: [ :index, :show ]

  def index
    @pending_events = Event.pending_events;
    @past_events = Event.past_events;

    respond_to do |format|
      format.html 
      format.xml  { render :xml => @events }
    end
  end

  def show
    @event = Event.find(params[:id])

    respond_to do |format|
      format.html 
      format.xml  { render :xml => @event }
    end
  end
  
  def new
    @event = Event.new

    respond_to do |format|
      format.html 
      format.xml  { render :xml => @event }
    end
  end
  
  def edit
    @event = Event.find(params[:id])
  end
  
  def create
    @event = Event.new(params[:event])

    respond_to do |format|
      if @event.save
        format.html { redirect_to(@event, :notice => 'Event was successfully created.') }
        format.xml  { render :xml => @event, :status => :created, :location => @event }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @event.errors, :status => :unprocessable_entity }
      end
    end
  end

  def update
    @event = Event.find(params[:id])

    respond_to do |format|
      if @event.update_attributes(params[:event])
        format.html { redirect_to(@event, :notice => 'Event was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @event.errors, :status => :unprocessable_entity }
      end
    end
  end
  
  def destroy
    @event = Event.find(params[:id])
    @event.destroy

    respond_to do |format|
      format.html { redirect_to(events_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/events/_form.html.erb
<%= form_for(@event) do |f| %>
  <% if @event.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@event.errors.count, "error") %> prohibited this event from being saved:</h2>

      <ul>
      <% @event.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name, "活动名称" %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :hold_date, "举办日期" %><br />
    <%= f.text_field :hold_date, {class: 'datepicker'} %>
  </div>
  <div class="field">
    <%= f.label :location, "举办地点" %><br />
    <%= f.text_field :location %>
  </div>
  <div class="field">
    <%= f.label :poster_url, "活动海报" %><br />
    <%= f.text_field :poster_url %>
  </div>
  <div class="field">
    <%= f.label :detail, "活动详情" %><br />
    <%= f.kindeditor :detail, :simple_mode => true %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/events/_past_event.html.erb
<div class="past_event event">
  <%= image_tag event.poster_url, alt: event.name %>
  <div class="event_brief">
    <h3><%= link_to event.name, event %></h3>
    <p>举办日期：<%= I18n.l(event.hold_date, format: :long) %></p>
    <p>举办地点：<%= event.location %></p>
  </div>
</div>

app/views/events/_pending_event.html.erb
<div class="pending_event event">
  <%= image_tag event.poster_url, alt: event.name %>
  <div class="event_brief">
    <h1><%= link_to event.name, event %></h1>
    <p>举办日期：<%= I18n.l(event.hold_date, format: :long) %></p>
    <p>举办地点：<%= event.location %></p>
    <p>活动简介：<%= truncate strip_tags(event.detail), length: 80, seperator: ' ' %></p>
    <p>
      当前有<%= link_to event.enrolments.count, event_path(event, anchor:"enrolments") %>人报名
      <%= link_to "我要报名", event_path(event, anchor: "new_enrolment") %>
    </p>
    <p>
      已提交<%= link_to event.topics.count, event_path(event, anchor:"topics") %>个话题
      <%= link_to "提交话题", event_path(event, anchor: "topics") %>
    </p>
  </div>
</div>

app/views/events/edit.html.erb
<h1>修改活动</h1>

<%= render 'form' %>

<%= link_to 'Show', @event %> |
<%= link_to 'Back', events_path %>

app/views/events/index.html.erb
<section id="pending_events">
<%= render collection: @pending_events, partial: 'pending_event', as: :event %>
</section>

<section id="past_events">
  <h2>往期活动</h2>
  <%= render collection: @past_events, partial: 'past_event', as: :event %>
</section>

app/views/events/new.html.erb
<h1>新建活动</h1>

<%= render 'form' %>

<%= link_to 'Back', events_path %>

app/views/events/show.html.erb
<h2><%= @event.name %></h2>
<%= social_share_button_tag(@event.name) %>
<%= link_to "修改", edit_event_path(@event) if admin? %>
<%= image_tag @event.poster_url, alt: @event.name, class: "poster" %>

<p>
  <b>举办时间:</b>
  <%= I18n.l(@event.hold_date, format: :long) %>
</p>

<p>
  <b>举办地:</b>
  <%= @event.location %>
</p>

<article id="eventDetail">
<%= sanitize @event.detail %>
</article>

<div id="enrolments">
  <h2>报名列表</h2>
  <ul>
    <%= render @event.enrolments %>
  </ul>
  <% if @event.pending_event? %>
    <%= form_for [@event, @event.enrolments.build], remote: true do |f| %>
      <% if !logged_in? %>
        <p>报名请先<%= link_to "登录", login_url %></p>
      <% elsif !@event.enrolments.find_by_user_id(current_user) %>
        <%= f.submit '我要报名' %>
      <% end %>
    <% end %>
  <% end %>
</div>

<div id="topics">
  <h2>已提交话题</h2>
  <%= render @event.topics %>
  <% if @event.pending_event? %>
    <div id="new_topic_form">
      <%= render 'topics/form' %>
    </div>
  <% end %>
</div>

<% if @event.past_event? %>
  <div id="records">
  <h2>活动记录</h2>
    <%= render @event.records %>
  </div>
<% end %>

<%= render template: "/layouts/_uyan" %>