config/routes.rb
OpenParty::Application.routes.draw do

  get "/about", to: "miscellaneous#about", as: :about

  resources :events, :except => :destroy do
    resources :enrolments
    resources :topics
  end
  resources :records

  match "/auth/:provider/callback", to: "sessions#create"
  match "/auth/failure", to: "sessions#new"
  get "/login", to: "sessions#new", as: :login
  get "/logout", to: "sessions#destroy", as: :logout

  resource :user, :only => [:show, :edit, :update, :destroy]
  get "/signup", to: "users#new", as: :signup

  resources :registrations, only: [:create]
  get "/checkin", to: "registrations#new", as: :checkin

  root :to => "events#index"

end

app/views/layouts/_user_nav.html.erb
<div id="userNav">
  <% if current_user %>
    <%= image_tag current_user.avatar_url, alt: "#{current_user.name}的头像", class: 'avatar' %>
    <span id="userName"><%= current_user.name %></span>
    <ul id="userMenu">
      <li><%= link_to "个人资料设置", edit_user_path %></li>
      <li><%= link_to "退出", logout_path %></li>
    </ul>
  <% else %>
    <a href="/login">登录</a>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>

  <head>
    <title>重庆Open Party</title>
    <%= stylesheet_link_tag    "application", :media => "all" %>
    <%= stylesheet_link_tag    "#{controller_name}", :media => "all" %>
    <%= javascript_include_tag "application" %>
    <%= javascript_include_tag "#{controller_name}" %>
    <%= csrf_meta_tags %>
    <meta charset="UTF-8">
  </head>

  <body>
    <div id="wrapper">

      <header>
      <h1><a href="/">重庆Open Party</a></h1>
      <span>发现身边的智慧</span>
      </header>

      <ul id="mainNav">
        <li><a href="/">首页</a></li>
        <li><a href="/events">活动</a></li>
        <li><a href="/records">记录</a></li>
        <li><a href="/checkin">签到</a></li>
        <li><a href="/about">关于</a></li>
        <li><%= render partial: 'layouts/user_nav' %></li>
      </ul>

      <% if flash[:error] %>
        <div class="error"><%= flash[:error] %></div>
      <% end %>

      <% if flash[:notice] %>
        <div class="notice"><%= flash[:notice] %></div>
      <% end %>

      <article id="content">
      <%= yield %>
      </article>

    </div>

    <footer>
    <p>
      本网站由<a href="http://mindhiking.info/">Merlin Ran</a>基于<a href="http://rubyonrails.org/">Ruby on Rails</a>创建
      <a href="http://jigsaw.w3.org/css-validator/check/referer">CSS Validator</a>
      <a href="http://validator.w3.org/check?uri=referer">XHTML Validator</a>
    </p>
    </footer>
    <%= render partial: 'layouts/google_analytics' %>
  </body>
</html>

app/views/layouts/surveyor_custom.html.erb
# encoding: UTF-8
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
  "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
<head>
  <meta http-equiv="content-type" content="text/html;charset=UTF-8" />
  <title>Survey: <%= controller.action_name %></title>
  <%= surveyor_includes %>
</head>
<body>
  <%= yield %>
</body>
</html>